version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: chatapp_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: chatapp_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: chatapp_web
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: chatapp_network