services:
  - type: web
    name: securechat
    runtime: python
    plan: free
    region: singapore
    buildCommand: ./build.sh
    startCommand: ./startup.sh
    rootDir: myproject
    envVars:
      - key: PORT
        value: "8000"
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: DJANGO_SECRET_KEY
        value: django-insecure-+2(ztamd_u#fv*i8107o8bi3sxchrfa=v*#q13r!_z^z!t6^*4
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: postgresql://chat_kyg2_user:Okf7zd4SgdoO963RViApZzeH6I340Dti@dpg-d1oen7je5dus73e56jdg-a/chat_kyg2
      - key: REDIS_URL
        value: redis://red-d1oe4obuibrs73cljeh0:6379
      - key: FERNET_SECRET_KEY
        value: _YeJIL4Ij4rVVXn_WDnpErLqDjj5uflG9m_mB1hV5Ww=
      - key: ALLOWED_HOSTS
        value: securechat-n4sp.onrender.com  # Update with your actual domain after deploy
