# Pull base image
ARG PYTHON_VERSION=3.11
FROM python:${PYTHON_VERSION}-slim


# Set working directory
WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . /app/

COPY docker/start.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 8000

ENTRYPOINT [ "/start.sh" ]