services:
  - type: web
    name: securechat
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: daphne myproject.asgi:application
    rootDir: myproject
    envVars:
      - key: DJANGO_SECRET_KEY
        value: django-insecure-+2(ztamd_u#fv*i8107o8bi3sxchrfa=v*#q13r!_z^z!t6^*4
      - key: DEBUG
        value: "True"
      - key: DB_ENGINE
        value: django.db.backends.postgresql
      - key: DB_NAME
        value: chat_kyg2
      - key: DB_USER
        value: chat_kyg2_user
      - key: DB_PASSWORD
        value: Okf7zd4SgdoO963RViApZzeH6I340Dti
      - key: DB_HOST
        value: dpg-d1oen7je5dus73e56jdg-a
      - key: DB_PORT
        value: "5432"
      - key: USE_POSTGRES
        value: "False"
      - key: REDIS_URL
        value: redis://red-d1oe4obuibrs73cljeh0:6379
      - key: FERNET_SECRET_KEY
        value: _YeJIL4Ij4rVVXn_WDnpErLqDjj5uflG9m_mB1hV5Ww=
      - key: ALLOWED_HOSTS
        value: securechat.onrender.com  # Update with your actual domain after deploy

